bug #301 fixed detection of console directory in symfony 3
sensiolabs/SensioDistributionBundle pull request #306
Opened 2017-01-06 13:17 UTC by mweibel

2017-01-06 13:39 UTC, HeahDude requested changes

2017-01-06 13:39 UTC, HeahDude commented on Composer/ScriptHandler.php
> +        if ($binDirExists && file_exists($binDirExists.DIRECTORY_SEPARATOR.'console')) {
This concatenation looks wrong, `$binDirExists` is a boolean not a path, am I missing something?

2017-01-06 13:49 UTC, mweibel commented on Composer/ScriptHandler.php
> +        if ($binDirExists && file_exists($binDirExists.DIRECTORY_SEPARATOR.'console')) {
d'oh ;) of course. Fixed.

2017-01-06 13:58 UTC, HeahDude approved these changes
👍

2017-01-06 13:59 UTC, HeahDude commented
To be merged in 4.0.

2017-01-06 14:09 UTC, romain-pierre commented
Why not returning the `bin` folder as default instead of the `app` one? So, making the same thing but testing first the presence of `app/console`. I'm experiencing the same issue as described in this case, but I think it's disturbing that the message said `Could not open input file: app/console` when I use Symfony 3.x and the console script has never been in the `app` folder.

Also, I don't understand why trying to run a script that we know absent from the folder. Maybe we can test the presence of this file instead of assuming (for a separated PR) and display a compliant error.

2020-01-06 11:55 UTC, fabpot commented
Closing this pull request as this bundle is now deprecated. Symfony Flex replaces this bundle.

2020-01-06 11:55 UTC, closed without merging