Adds the environment parameter to ::executeCommand
sensiolabs/SensioDistributionBundle pull request #310
Opened 2017-02-06 11:35 UTC by schneekatze

2017-02-06 11:38 UTC, stof requested changes

2017-02-06 11:38 UTC, stof commented on Composer/ScriptHandler.php
> +    protected static function executeCommand(Event $event, $consoleDir, $cmd, $env = null, $timeout = 300)
adding the parameter in the middle of the signature is a BC break

2017-02-06 12:33 UTC, schneekatze commented on Composer/ScriptHandler.php
> +    protected static function executeCommand(Event $event, $consoleDir, $cmd, $env = null, $timeout = 300)
Fixed

2017-07-04 09:27 UTC, jaymecd commented on Composer/ScriptHandler.php
> +        $process = new Process($php.($phpArgs ? ' '.$phpArgs : '').' '.$console.' '.$cmd, null, $env, null, $timeout);
Faced same issue today, but harder:
`ScriptHandler` completely ignores `ENV` and if there is a custom login (based on ENV) in kernel, eg. `AppKernel`, then '$_ENV' in child process would be empty and app flow is affected.

Suggest to pass `ENV` from parent to child procs:

```php
$env = array_merge($_ENV, (array) $env);
```

2020-01-06 11:55 UTC, fabpot commented
Closing this pull request as this bundle is now deprecated. Symfony Flex replaces this bundle.

2020-01-06 11:55 UTC, closed without merging